Terrain Producer Refactor
meta4d-me/AssetPipeline pull request #109
Opened 2023-01-30 07:42 UTC by ChaoSXDemon

This branch reworks TerrainProducer such that we can create a consumer on the editor side to create terrain via ECS system.

2023-01-30 14:10 UTC, T-rvw commented on private/Math/MeshGenerator.cpp
> -std::optional<Mesh> MeshGenerator::Generate(const Box& box, const VertexFormat& vertexFormat)
We should not use `TBox<float>` directly. Need to revert.

2023-01-30 14:10 UTC, T-rvw commented on private/Math/MeshGenerator.cpp
> -std::optional<Mesh> MeshGenerator::Generate(const Plane& plane, float width, float height, const VertexFormat& vertexFormat)
Ditto. Need to revert.

2023-01-30 14:10 UTC, T-rvw commented on private/Math/MeshGenerator.cpp
> -std::optional<Mesh> MeshGenerator::Generate(const Plane& plane, float width, float height, const VertexFormat& vertexFormat)
Ditto. Need to revert.

2023-01-30 14:10 UTC, T-rvw commented on private/Math/MeshGenerator.cpp
>  }
This function already deleted. Why you need it?

2023-01-30 14:12 UTC, T-rvw commented
@ChaoSXDemon As <format> doesn't support in Linux g++ so please use other ways to replace it for `AssetPipelineCore` part.
And MeshGenerator should revert changes.

2023-02-02 04:06 UTC, ChaoSXDemon commented on private/Math/MeshGenerator.cpp
> -std::optional<Mesh> MeshGenerator::Generate(const Box& box, const VertexFormat& vertexFormat)
This cause compile error for me. I can try again and paste the error here

2023-02-02 04:06 UTC, ChaoSXDemon commented on private/Math/MeshGenerator.cpp
>  }
Perhaps merge error then, was experiencing linker error

2023-02-02 08:15 UTC, ChaoSXDemon commented
@T-rvw , I added implementation of string_format and removed dependency for std::format

2023-02-03 02:48 UTC, T-rvw requested changes
Move public/Scene/TerrainTypes.h to TerrainProducer folder? Terrain is a specified feature, not generic to put in the public/scene folder.
And MaterialTextureType I think it doesn't need to add Terrain type. We want to make AssetPipeline look like a very generic lib for scene graph data. Every feature specfied classes and types should put in its Producer/Consumer folder.

2023-02-03 03:56 UTC, ChaoSXDemon commented
I thought we want to edit terrain and that means on the editor side, people need access to the structs in TerrainTypes.h. As for material type, we need that to render terrain as terrain will be constructed with StaticMeshComponent + MaterialComponent and these two alone can't tell the difference between different kinds of meshes.

2023-02-03 04:40 UTC, T-rvw commented
> I thought we want to edit terrain and that means on the editor side, people need access to the structs in TerrainTypes.h. As for material type, we need that to render terrain as terrain will be constructed with StaticMeshComponent + MaterialComponent and these two alone can't tell the difference between different kinds of meshes.

Yes. You can also access Terrain type data in the TerrainProducer folder. Just may need to edit editor.lua makefile.

For material type, you may misunderstand something? We will create explicit MaterialType objects in the editor side. See `engine::MaterialType::GetPBRMaterialType()`. You should add a TerrainMaterialType following this pattern. No need to change other things in the AssetPipeline.

2023-02-05 05:01 UTC, merged